### ISSUE TITLE
Table iconation.transaction shows weird amounts

### ISSUE THREAD

**Issue by nickhessing** [iconation/aegis#2]
Hi Guys from Iconation,

I'm new to github so if you have suggestions on how to report issues better, let me know.
Please see attached the issue with the column 'amount'. 

Regards,
Nick

![issue 1](https://user-images.githubusercontent.com/33545080/78826551-fac46980-79e1-11ea-8328-380d06d63066.JPG)

**Comment by Spl3en** [comment]
These amounts are displaied in loops.
1 ICX = 10^18 loops (1000000000000000000)
